dataset_path:       "./datasets/300W-WFLW"
test_txt_path:      "./datasets/300W-WFLW/test.txt"
train_txt_path:     "./datasets/300W-WFLW/train_300W-WFLW-lmk12-42dot-pha-v3.txt"
mean_lmk_txt_path:  "./datasets/300W-WFLW/mean-lmk_300W.txt"

indices: &indices_anchor
  [  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,   # ( 1-17): jawline
    18, 19, 20, 21, 22,                                                   # (18-22): right eyebrow
    23, 24, 25, 26, 27,                                                   # (23-27): left eyebrow
    28, 29, 30, 31,                                                       # (28-31): nose bridge
    32, 33, 34, 35, 36,                                                   # (32-36): nostrils
    37, 38, 39, 40, 41, 42,                                               # (37-42): right eye
    43, 44, 45, 46, 47, 48,                                               # (43-48): left eye
    49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,                       # (49-60): outer lips
    61, 62, 63, 64, 65, 66, 67, 68,                                       # (61-68): inner lips
  ]

flip_indices: &flip_indices_anchor
  [ 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,   # ( 1-17): jawline
    27, 26, 25, 24, 23,                                                   # (23-27): left eyebrow
    22, 21, 20, 19, 18,                                                   # (18-22): right eyebrow
    28, 29, 30, 31,                                                       # (28-31): nose bridge
    36, 35, 34, 33, 32,                                                   # (32-36): nostrils
    46, 45, 44, 43, 48, 47,                                               # (43-48): right eye
    40, 39, 38, 37, 42, 41,                                               # (37-42): left eye
    55, 54, 53, 52, 51, 50, 49, 60, 59, 58, 57, 56,                       # (49-60): outer lips
    65, 64, 63, 62, 61, 68, 67, 66,                                       # (61-68): inner lips
  ]

indices_eyes: &indices_eyes_anchor
  [ 1,  2,  3,  4,  5,  6,                  # (1- 6): right eye
    7,  8,  9, 10, 11, 12,                  # (7-12): left eye
  ]

flip_indices_eyes: &flip_indices_eyes_anchor
  [ 10, 9, 8, 7, 12, 11,                    # (7-12): right eye
     4, 3, 2, 1,  6,  5,                    # (1- 6): left eye
  ]

selected_indices: *flip_indices_eyes_anchor # [flip_indices_anchor, flip_indices_eyes_anchor]
